stages:
  - install
  - deploy

install:
  image: registry.wndv.co/node:18
  stage: install
  script:
    - yarn install
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - node_modules
    policy: pull-push

publish to nexus:
  image: registry.wndv.co/node:18
  stage: deploy
  only: [main, dev]
  when: manual
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - node_modules
    policy: pull
  script:
    - yarn release
  environment:
    name: $CI_COMMIT_BRANCH
